config/routes.rb
Rails.application.routes.draw do
  resources :efemerides
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/efemeride.rb
class Efemeride < ApplicationRecord
    mount_uploader :photo, ImageUploader
    scope :requests_today, -> { where created_at: Time.current.beginning_of_day..Time.current.end_of_day }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/efemerides_controller.rb
class EfemeridesController < ApplicationController
  before_action :set_efemeride, only: %i[ show edit update destroy ]

  # GET /efemerides or /efemerides.json
  def index
    if params[:search].present? 
      @efemerides = Efemeride.where("categories ILIKE ?", "%#{params[:search]}%")
    else
      @efemerides = Efemeride.today
      #@efemerides = Efemeride.where(date: Date.today.all_day) 
    end
      #if params[:search].present?
      #  @efemerides = Efemeride.where("categories ILIKE ?", "%#{params[:search]}%")
      #end
  end

  # GET /efemerides/1 or /efemerides/1.json
  def show
  end

  # GET /efemerides/new
  def new
    @efemeride = Efemeride.new
  end

  # GET /efemerides/1/edit
  def edit
  end

  # POST /efemerides or /efemerides.json
  def create
    @efemeride = Efemeride.new(efemeride_params)

    respond_to do |format|
      if @efemeride.save
        format.html { redirect_to efemeride_url(@efemeride), notice: "Efemeride was successfully created." }
        format.json { render :show, status: :created, location: @efemeride }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @efemeride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /efemerides/1 or /efemerides/1.json
  def update
    respond_to do |format|
      if @efemeride.update(efemeride_params)
        format.html { redirect_to efemeride_url(@efemeride), notice: "Efemeride was successfully updated." }
        format.json { render :show, status: :ok, location: @efemeride }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @efemeride.errors, status: :unprocessable_entity }
      end
    end
  end

  def find_schedules
    if start_params = params[:start_date] && end_params = params[:end_date]
     start_date = DateTime.new(start_params["year"].to_i, start_params["month"].to_i, start_params["day"].to_i)
     end_date = DateTime.new(end_params["year"].to_i, end_params["month"].to_i, end_params["day"].to_i)
     @efemerides = Efemeride.find(:all, :conditions => {:coursedate => start_date..end_date})  
    end
  end

  # DELETE /efemerides/1 or /efemerides/1.json
  def destroy
    @efemeride.destroy

    respond_to do |format|
      format.html { redirect_to efemerides_url, notice: "Efemeride was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_efemeride
      @efemeride = Efemeride.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def efemeride_params
      params.require(:efemeride).permit(:date, :categories, :comments, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/efemerides_helper.rb
module EfemeridesHelper
end

app/views/efemerides/_efemeride.html.erb
<div id="<%= dom_id efemeride %>">
  <p>
    <strong>Date:</strong>
    <%= efemeride.date %>
  </p>

  <p>
    <strong>Categories:</strong>
    <%= efemeride.categories %>
  </p>

  <p>
    <strong>Comments:</strong>
    <%= efemeride.comments %>
  </p>

  <img src="<%= efemeride.photo%>">
</div>
<br>

app/views/efemerides/_filter_params.html.erb
<%= form_for("filter_params", html: { method: "get" }) do | form | %>
  <div class="row col-md-12">
    <div class="pull-left col-md-2">
      <h4><%= "Prueba" %></h4>
    </div>
    <div class="col-md-10 pull-right">
      <div class="col-md-2 pull-right">
        <%= form.submit "Filtrar" %>
      </div>
      <div class="col-md-4 pull-right">
        <div class="col-md-6">
          <%= form.text_field :date_from, data:
          {:provide => "datepicker", 'date-format' => 'dd/mm/yyyy',
          :language => "es"}, class: "form-control",
          placeholder: "dd/mm/aaaa", autocomplete: 'off', value: @start_date  %>
        </div>
        <div class="col-md-6">
          <%= form.text_field :date_to, data:
          {:provide => "datepicker", 'date-format' => 'dd/mm/yyyy',
          :language => "es"}, class: "form-control",
          placeholder: "dd/mm/aaaa", autocomplete: 'off', value: @end_date  %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/efemerides/_form.html.erb
<%= form_with(model: efemeride) do |form| %>
  <% if efemeride.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(efemeride.errors.count, "error") %> prohibited this efemeride from being saved:</h2>

      <ul>
        <% efemeride.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "Fecha", style: "display: block" %>
    <%= form.datetime_field :date %>
  </div>

  <div>
    <%= form.label "Categoria", style: "display: block" %>
    <%= form.text_field :categories %>
  </div>

  <div>
    <%= form.label "Comentario", style: "display: block" %>
    <%= form.text_area :comments %>
  </div>

  <div>
    <%= form.label "Imagen", style: "display: block" %>
    <%= form.file_field :photo %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/efemerides/edit.html.erb
<h1>Editing efemeride</h1>

<%= render "form", efemeride: @efemeride %>

<br>

<div>
  <%= link_to "Show this efemeride", @efemeride %> |
  <%= link_to "Back to efemerides", efemerides_path %>
</div>

app/views/efemerides/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="efemerides">
<% content_for :title, 'Listado de efemerides' %>
  <input type="text" id="rangepicker"  value="01/01/2018 - 01/15/2018" />
  <br> 
  <%= render "filter_params" %>
  <form>
    <div class="form-group form-inline col-md-3" style="margin-top: 20px">
      <div class="input-group">
        <% if params[:search].present? %>
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-search"></i></span>
          <input type="text" name="search" id="search" placeholder="Buscar por categoría" value="<%= params[:search] %>" class='form-control'>
        </div>
        <% else %>
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-search"></i></span>
          <input type="text" name="search" id="search" placeholder="Buscar por categoría" class='form-control'>
        </div>
        <% end %>
        <span class="input-group-btn">
          <button class="btn btn-primary" type="submit"><span class="fa fa-search" aria-hidden="true">
            </span> Buscar</button>
        </span>
      </div>
    </div>
  </form>
</div>
<div class="panel panel-default">
  <div class="row">
    <div class="pull-right" style="margin-top: 20px; margin-right: 20px">
      <%= button_to  "NUEVO EFEMERIDE", new_efemeride_path(), method: :get, class: "btn btn-primary" %>
    </div>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="display table table-bordered table-hover table-striped">
        <thead>
          <tr>
            <th>Fecha</th>
            <th>Categoria</th>
            <th>Comentario</th>
            <th>Imagen</th>
            <th>Opciones</th>
          </tr>
        </thead>
        <tbody>
          <% @efemerides.each do |efemeride|%>
          <tr>
            <td>
              <%=efemeride.date.strftime("%d/%m/%Y %H:%M") + " hrs" %>
            </td>
            <td>
              <%=efemeride.categories%>
            </td>
            <td>
              <%=efemeride.comments%>
            </td>
            <td style="text-align: center">
              <img src="<%= efemeride.photo%>" style="width:20%; height:20%;">
            </td>
            <td>
              <%= link_to "Ver", efemeride %>
            </td>
          </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script>
  $("#rangepicker").daterangepicker({}, function(start, end, label) {
    console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
  });
</script>

app/views/efemerides/new.html.erb
<h1>Nuevo efemeride</h1>

<%= render "form", efemeride: @efemeride %>

<br>

<div>
  <%= link_to "Regresar", efemerides_path %>
</div>

app/views/efemerides/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @efemeride %>

<div>
  <%= button_to "Eliminar efemeride", @efemeride, method: :delete %>
  <br>
  <br>
  <%= link_to "Editar efemeride", edit_efemeride_path(@efemeride) %> |
  <%= link_to "Regresar", efemerides_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Efemerid</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>